# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [ ]:
## Assignment 1: Array Creation and Manipulation
#1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

import numpy as np 
#1
arr = np.random.randint(1, 21,size = (5,5))
print("ARRAY :",arr)

arr[:,2] = 1
print("Modified Array:",arr)


#2
arr2 = np.arange(1,17).reshape(4,4)
print("Second Array",arr2)

np.fill_diagonal(arr2,0)
print("Modified Second array",arr2)

In [ ]:
### Assignment 2: Array Indexing and Slicing

#1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
#2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

new_arr = np.arange(1,37).reshape(6,6)
print("Array",new_arr)

sub_arr = new_arr[2:5,1:4]
print("Sub-Array of the  above array",sub_arr)

num_arr = np.random.randint(50,size=(5,5))
print('original Array',num_arr)
border_elements = np.concatenate((num_arr[0, :], num_arr[-1, :], num_arr[1:-1, 0], num_arr[1:-1, -1]))
print("Border elements:")
print(border_elements)


In [ ]:
### Assignment 3: Array Operations

#1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

N1 = np.random.randint(1,50,size = (3,4))
N2 = np.random.randint(1,50,size=(3,4))
print("N1:",N1)
print("N2:",N2)
print("Element wise Addition",N1+N2)
print("Element wise Subtraction",N1-N2)
print("Element wise Multiplication",N1*N2)
print("Element wise Division",N1/N2)


In [10]:
### Assignment 3: Array  
#2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.
Num_arr = np.arange(1,17).reshape(4,4)
print("original array",Num_arr)

row_sum = np.sum(Num_arr,axis = 1)
col_sum = np.sum(Num_arr,axis =0)
print("row wise sum",row_sum)
print("col wise",col_sum)

original array [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
row wise sum [10 26 42 58]
col wise [28 32 36 40]


In [ ]:
## Assignment 4: Statistical Operations

#1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
numbers = np.random.randint(1,100,size = (5,5))
print("Original array",numbers)

mean = np.mean(numbers)
print("Mean of the array",mean)
median = np.median(numbers)
print("Median of the array",median)
std_var = np.std(numbers)
print("Standard Varience of the array",std_var)
var = np.var(numbers)
print("Varience of the Array",var)

In [20]:
# Assignment 4: Statistical Operations
#2. Create a NumPy array of shape (3, 3) with values from 1 to 9. 
# Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

Array = np.arange(1,10).reshape(3,3)
print("Array:",Array)

mean = np.mean(Array)
std = np.std(Array)
Normalized_Array = Array - mean/std
print("Normalized Array",Normalized_Array)


Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized Array [[-0.93649167  0.06350833  1.06350833]
 [ 2.06350833  3.06350833  4.06350833]
 [ 5.06350833  6.06350833  7.06350833]]


In [22]:
## Assignment 5: Broadcasting
#1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

Arr = np.random.randint(1,20,size = (3,3))
print('2D Array',Arr)
Arr_1d = [1,2,3]
print("1D Array",Arr_1d)

resulting_Array = Arr + Arr_1d
print("result",resulting_Array)


2D Array [[16 14 15]
 [16 18  7]
 [ 1  3 12]]
1D Array [1, 2, 3]
result [[17 16 18]
 [17 20 10]
 [ 2  5 15]]


In [ ]:
### Assignment 5: Broadcasting
#2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

Arr = np.random.randint(1,50,size = (4,4))
print("2d Array",Arr)
Arr_1D = np.random.randint(1,10,size=(4,))
print("1d array",Arr_1D)

resulting_Array = Arr - Arr_1D
print("result of subtraction",resulting_Array)


In [ ]:
### Assignment 6: Linear Algebra
#1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

matrix = np.arange(1,10).reshape(3,3)
print("Matrix:",matrix)

determinant = np.linalg.det(matrix)
print("Determinant of the matrix",determinant)
Inverse = np.linalg.inv(matrix)
print("Inverse of the matrix",Inverse)
eigenvalues = np.linalg.eigvals(matrix)
print("Eigenvalues",eigenvalues)


Matrix: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Determinant of the matrix 6.66133814775094e-16
Inverse of the matrix [[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]
Eigenvalues [ 1.61168440e+01 -1.11684397e+00 -4.22209278e-16]


In [30]:
### Assignment 6: Linear Algebra
#2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.
n1 =np.random.randint(1,20,size=(2,3))
print("n1 ",n1)
n2 = np.random.randint(1,20,size=(3,2))
print("n2 ",n2)

mat_multiply = np.dot(n1,n2)
print("resulting matrix after multiplication",mat_multiply)


n1  [[ 5  4 18]
 [ 5 13 16]]
n2  [[10 12]
 [14  7]
 [ 6 15]]
resulting matrix after multiplication [[214 358]
 [328 391]]


In [37]:
## Assignment 7: Advanced Array Manipulation
#1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
Array = np.arange(1,10).reshape((3,3))
print("original array",Array)

Reshaped_arr = Array.reshape((1,9))
print("Reshaped Array",Reshaped_arr)
Reshaped_arr1 = Array.reshape((9,1))
print("Reshaped Array",Reshaped_arr1)

original array [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped Array [[1 2 3 4 5 6 7 8 9]]
Reshaped Array [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
## Assignment 7: Advanced Array Manipulation
#2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).
Num_arr = np.random.randint(1,25,size=(5,5))
print("original array",Num_arr)

flattened = Num_arr.flatten()
print('flatten array',flattened)

reshaped = flattened.reshape(5,5)
print("Reshaped Array",reshaped)

In [ ]:
## Assignment 8: Fancy Indexing and Boolean Indexing
#1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

num = np.random.randint(1,21,size= (5,5))
print("original array",num)

corners = num[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)


original array [[ 4 17  2 11 12]
 [16  1 13 11  3]
 [12 13  4  4 15]
 [ 9  8 18  7 17]
 [19 13  8 13 15]]
Corner elements:
[ 4 12 19 15]


In [ ]:
# Assignment 8: Fancy Indexing and Boolean Indexing
#2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.
Array = np.random.randint(1,30,size=(4,4))
print("original array",Array)

Array[Array > 10] = 10
print("Modified array:",Array)



In [46]:
### Assignment 9: Structured Arrays
#1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:",data)

sorted_data = np.sort(data, order='age')
print("Sorted array by age:",sorted_data)


Original array: [('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age: [('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [ ]:
### Assignment 9: Structured Arrays
#2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:",data)

distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:",distances)


Original array: [(1, 2) (3, 4) (5, 6)]
Euclidean distances: [[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [ ]:
### Assignment 10: Masked Arrays
#1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
import numpy.ma as ma
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:",array)
print("Masked array:",masked_array)
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array: [[10 17 11 20]
 [ 7 13 17 12]
 [20 16  2 20]
 [ 6  8 20 16]]
Masked array: [[10 -- -- --]
 [7 -- -- --]
 [-- -- 2 --]
 [6 8 -- --]]
Sum of unmasked elements: 33


In [52]:

### Assignment 10: Masked Arrays
#2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[11 14  6]
 [19 20 15]
 [10  9  8]]
Masked array:
[[-- 14 6]
 [19 -- 15]
 [10 9 --]]
Modified masked array:
[[12 14  6]
 [19 12 15]
 [10  9 12]]
